94 add images
fga-eps-mds/2021.1-Multilind-admin-website pull request #6
Opened 2021-11-05 00:01 UTC by ingridSCarvalho

Eu como usuário desejo adicionar imagens em uma palavra para tornar claro seu entendimento.

### Tarefas
- [x] Dar opção de inserir imagens no cadastro de palavras

### Critérios de aceitação
- [x] Opção de inserir imagens
- [x] Associar as imagens às palavras
![telaModal](https://user-images.githubusercontent.com/69825746/140436444-edb2f34f-2e41-42fa-8808-9e8062d85144.png)

2021-11-06 21:46 UTC, GabrielDVpereira approved these changes

2021-11-06 21:49 UTC, GabrielDVpereira commented on src/components/AddImage/index.js
> +  // const palavraTeste = {
remover comentário

2021-11-06 21:49 UTC, GabrielDVpereira commented on src/config/files-api.js
> +  baseURL: 'http://localhost:5000/',
passar url para o .env e usar o process.env aqui

2021-11-06 21:49 UTC, GabrielDVpereira commented on src/services/fileServices/imageService.js
> +    console.log(idPalavra, formData)
remover log

2021-11-06 22:07 UTC, GabrielDVpereira requested changes
Poderiam fazer um passo a passo de como testar essa página?

2021-11-06 22:07 UTC, GabrielDVpereira commented on src/routes/routes.js
> +import { AddImages } from '../components'
AddImages deveria ser uma page, se é usada diretamente nas rotas

2021-11-07 00:55 UTC, CarlosZoft commented on src/routes/routes.js
> +import { AddImages } from '../components'
Colocamos nas routes para testar, vai ser usada como um modal

2021-11-08 00:39 UTC, micaellagouveia approved these changes

2021-11-08 03:30 UTC, merged